main:
  components_repository: "components"
  project_name: nyc_airbnb
  experiment_name: development
  steps: all

etl:
  group: "etl"
  eda:
    job_type: "eda"
  download:
    job_type: "download_file"
    sample: "sample1.csv"
    output_artifact: "sample.csv"
    output_type: "raw_data"
    output_desc: "Raw file as downloaded"
  basic_cleaning:
    job_type: "basic_cleaning"
    input_artifact: "sample.csv:latest"
    output_artifact: "clean_sample.csv"
    output_type: "clean_data"
    filters: # [column, min, max] - use null for no bound
      - [price, 10, 350]
      #- [minimum_nights, 1, 365]
      #- [availability_365, 1, null]
      #- [longitude, -74.25, -73.50]
      #- [latitude, 40.5, 41.2]
  data_check:
    input_artifact: "clean_sample.csv:latest"
    ref_artifact: "clean_sample.csv:latest"
    kl_threshold: 0.2
    min_price: 10
    max_price: 350

data_split:
  input_artifact: "clean_sample.csv:latest"
  trainval_artifact: "trainval_data.csv"
  test_artifact: "test_data.csv"

test_regression_model:
  input_model: "random_forest_export:prod"
  input_artifact: "test_data.csv:latest"

modeling:
  input_artifact: "trainval_data.csv:latest"
  output_artifact: "random_forest_export"
  test_size: 0.2
  val_size: 0.2
  random_seed: 42
  stratify_by: "neighbourhood_group"
  max_tfidf_features: 5
  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 4
    min_samples_leaf: 3
    n_jobs: -1
    criterion: squared_error
    max_features: 0.5
    oob_score: true